//> using scala "3"
//> using dep "dev.zio::zio::2.0.22"
//> using dep "dev.zio::zio-http::3.0.0-RC6"
//> using dep "dev.zio::zio-json::0.6.2"
//> using dep "com.softwaremill.sttp.tapir::tapir-zio-http-server::1.10.4"
//> using dep "com.softwaremill.sttp.tapir::tapir-json-zio::1.10.4"
//> using dep "dev.zio::zio-metrics-connectors::2.3.1"
//> using dep "dev.zio::zio-metrics-connectors-prometheus::2.3.1"
