//> using scala "3"
//> using dep "dev.zio::zio::2.0.21"
//> using dep "dev.zio::zio-json::0.6.2"
//> using dep "dev.zio::zio-lambda::1.0.4"
//> using dep "dev.zio::zio-lambda-event::1.0.4"
//> using dep "dev.zio::zio-dynamodb::1.0.0-RC2"
//> using dep "com.softwaremill.sttp.client3::zio::3.9.5"
//> using dep "com.softwaremill.sttp.client3::zio-json::3.9.5"
